# Generated by Django 3.2 on 2021-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image', models.CharField(max_length=2000)),
            ],
        ),
    ]
