# Generated by Django 3.2 on 2021-05-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210502_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='discount',
            new_name='Discount',
        ),
    ]
